Listing taxonomy groups and items now responds with proper API error response.
Kentico/kontent-delivery-sdk-net pull request #328
Opened 2022-05-12 18:45 UTC by MiroKentico

### Motivation

Fixes #326

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

TBD

2022-05-19 12:35 UTC, Sevitas requested changes
I have just few notes:
1. Have you considered creating another constructor for responses (eg. DeliveryItemListingResponse) with just an ApiResponse param? It could save us setting those null values in the client.
2. Why there is no _succes check_ for _GetItemAsync, GetTypeAsync, GetContentElementAsync, GetTaxonomyAsync_ methods?
3. I think it would be better to move _succes check_ before assignement to the content variable.

2022-05-26 07:15 UTC, MiroKentico commented
> I have just few notes:
> 
>     1. Have you considered creating another constructor for responses (eg. DeliveryItemListingResponse) with just an ApiResponse param? It could save us setting those null values in the client.
> 
>     2. Why there is no _succes check_ for _GetItemAsync, GetTypeAsync, GetContentElementAsync, GetTaxonomyAsync_ methods?
> 
>     3. I think it would be better to move _succes check_ before assignement to the content variable.

1. No, I haven't thought about these constructors for null values. I will think about it and reach you to discuss it.
2. The reason is, that implementation was already done in a way, that they already produced correct error response  ... and added unit tests prove it. I will think about putting that `IsSuccess` check, but if I will put it there, it would be more for some code standardization than pure necessity.
3. You are right, it would be better place (to avoid doing not necessary code in these error cases). I will move this check as close to actual response retrieval where the code place is sub-optimal (case that you wrote).

2022-05-26 10:33 UTC, MiroKentico commented
> > I have just few notes:
> > ```
> > 1. Have you considered creating another constructor for responses (eg. DeliveryItemListingResponse) with just an ApiResponse param? It could save us setting those null values in the client.
> > 
> > 2. Why there is no _succes check_ for _GetItemAsync, GetTypeAsync, GetContentElementAsync, GetTaxonomyAsync_ methods?
> > 
> > 3. I think it would be better to move _succes check_ before assignement to the content variable.
> > ```
> 
>     1. No, I haven't thought about these constructors for null values. I will think about it and reach you to discuss it.
> 
>     2. The reason is, that implementation was already done in a way, that they already produced correct error response  ... and added unit tests prove it. I will think about putting that `IsSuccess` check, but if I will put it there, it would be more for some code standardization than pure necessity.
> 
>     3. You are right, it would be better place (to avoid doing not necessary code in these error cases). I will move this check as close to actual response retrieval where the code place is sub-optimal (case that you wrote).



> I have just few notes:
> 
>     1. Have you considered creating another constructor for responses (eg. DeliveryItemListingResponse) with just an ApiResponse param? It could save us setting those null values in the client.
> 
>     2. Why there is no _succes check_ for _GetItemAsync, GetTypeAsync, GetContentElementAsync, GetTaxonomyAsync_ methods?
> 
>     3. I think it would be better to move _succes check_ before assignement to the content variable.



> > I have just few notes:
> > ```
> > 1. Have you considered creating another constructor for responses (eg. DeliveryItemListingResponse) with just an ApiResponse param? It could save us setting those null values in the client.
> > 
> > 2. Why there is no _succes check_ for _GetItemAsync, GetTypeAsync, GetContentElementAsync, GetTaxonomyAsync_ methods?
> > 
> > 3. I think it would be better to move _succes check_ before assignement to the content variable.
> > ```
> 
>     1. No, I haven't thought about these constructors for null values. I will think about it and reach you to discuss it.
> 
>     2. The reason is, that implementation was already done in a way, that they already produced correct error response  ... and added unit tests prove it. I will think about putting that `IsSuccess` check, but if I will put it there, it would be more for some code standardization than pure necessity.
> 
>     3. You are right, it would be better place (to avoid doing not necessary code in these error cases). I will move this check as close to actual response retrieval where the code place is sub-optimal (case that you wrote).

Points 1. and 3. are now implemented, for point 2. is opened discussion within SDK maintainer team.

2022-06-16 11:06 UTC, Sevitas submitted a review, later dismissed
Just a nitpick, otherwise LGTM.

2022-06-16 11:06 UTC, Sevitas commented on Kentico.Kontent.Delivery/ContentItems/DeliveryItemResponse.cs
>          {
using System.Collections.Generic; - unused

2022-06-16 11:23 UTC, merged

2022-06-16 11:23 UTC, MiroKentico commented on Kentico.Kontent.Delivery/ContentItems/DeliveryItemResponse.cs
>          {
Removed.